version: 2.1
orbs:
    katalon-studio: katalon/katalon-studio@23.0.11
environment:
      My_Automation: f1a6b482-3a0f-4dde-bfbc-a01f1f81a148
    
workflows:
  build:
    jobs:
        - katalon-studio/run:
                version: "latest"
                command_arguments: '-browserType="Chrome" -retry=2 -statusDelay=15 -testSuitePath="Test Suites/Keypath_Testsuite"'
