version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.11
workflows:
  build:
    jobs:
      - katalon-studio/run:
          version: latest
          command_arguments: >
            katalon-execute.sh -apiKey=f1a6b482-3a0f-4dde-bfbc-a01f1f81a148 -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test Suites/Keypath_Testsuite.ts'
