version: 2.1

jobs:
  build:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Run Katalon tests
          command: |
            # Run your Katalon tests here
            katalon-execute.sh -projectPath="/Automation_Keypath" -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Keypath_Testsuite" -apiKey="f1a6b482-3a0f-4dde-bfbc-a01f1f81a148"
